layout_spectrum: 0.900376
color:
  saturation: 0.8389724
  brandStrength: 0.8408521
  lightness: 0.5488722
  brandColors:
    - '#472C17'
    - '#6C503B'
    - '#375F6A'
    - '#BC9A8F'
    - '#39BCCB'
  rhythmicContrast: 0.6196742
typography_spectrum: 0.1616541
name: Chris vs Liza
