name: Chris vs Liza
favicon: null
layout_spectrum: 0.99804
typography_spectrum: 0.1616541
title: Its about perspective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01E3F7'
    - '#9A01DA'
    - '#EAE4E4'
    - '#031309'
    - '#025C26'
  brandStrength: 0
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
