layout_spectrum: 0.900376
color:
  saturation: 0.8389724
  brandStrength: 0.8182957
  lightness: 0.5488722
  brandColors:
    - '#01E3F7'
    - '#9A01DA'
    - '#EAE4E4'
    - '#031309'
    - '#025C26'
  rhythmicContrast: 0.6196742
typography_spectrum: 0.1616541
name: Chris vs Liza
