name: Chris vs Liza
favicon: null
layout_spectrum: 0.73192
typography_spectrum: 0.1616541
title: Its about perspective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01E3F7'
    - '#9A01DA'
    - '#EAE4E4'
    - '#031309'
    - '#025C26'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6196742
purpose: []
